name: grupo_casadecor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3


environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.11
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  http: ^1.4.0
  get: ^4.7.2
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Adicione este pacote para gerar ícones
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

# Configuração para gerar os ícones do app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.jpg
  remove_alpha_ios: true
